######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 23 09:22:06 2014
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += MyClient.hpp
SOURCES += main.cpp MyClient.cpp
