######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 23 14:27:46 2014
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += MyServer.hpp
SOURCES += main.cpp MyServer.cpp
